name: NetworkingDream
tagline: >
  A quiet place for lifelong learning, thoughtful tinkering,
  and enjoying the journey of computing.

author:
  name: Steven
  avatar: https://www.gravatar.com/avatar/eba846a559694d99b964d649948472fc?s=64&d=mp